### ISSUE TITLE
not all pages are downloaded

### ISSUE THREAD

**Issue by SyedAfnaan** [tokland/pysheng#36]
after installing pyshen
used this code:
$ pyshen https://play.google.com/books/reader?id="book id"
my book contains 140 pages.... but this codei cud only see 30 pages

**Comment by michaelcoyote** [comment]
This is a limitation of google books sadly  :-(


On January 8, 2019 at 3:36:43 AM, SyedAfnaan (notifications@github.com)
wrote:

after installing pyshen
used this code:
$ pyshen https://play.google.com/books/reader?id="book id"
my book contains 140 pages.... but this codei cud only see 30 pages

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pysheng/pysheng/issues/36>, or mute the thread

**Comment by SyedAfnaan** [comment]
any other way to download books from play books on linux.... i am using deepin 15.8

**Comment by michaelcoyote** [comment]
Sadly this appears to be a limitation of google books.  Probably an intentional one.
